### ISSUE TITLE
Generics를 사용할 때 primitive 타입을 사용하는 방법

### ISSUE THREAD

**Issue by cmpark0126** [cmpark0126/wicwiu-rust#1]
안녕하세요 강지훈 교수님.

현재 wicwiu를 rust로 구현하는 과정에서 Generic을 c++의 template 처럼 사용하고자 하였으나, 일반적인 i16, i32, f32.. 등과 같은 primitive type에 대해서 바로 generic을 적용하는 방법을 모르겠어 이슈를 남깁니다.

우선은 다음과 같은 접근을 사용하고 있습니다.

1. 우선 구체적으로 숫자를 의미하는 trait 구축 및 사용하고자 하는 primitive type에 대해서 각각 구현
https://github.com/cmpark0126/wicwiu-rust/blob/e13d6a7fa623691ab66a2dd2500f9f81674baaf1/src/numeric.rs#L1-L13

2. Generic을 사용하는 structure에 대해서 위의 Trait 사용
https://github.com/cmpark0126/wicwiu-rust/blob/e13d6a7fa623691ab66a2dd2500f9f81674baaf1/src/tensor.rs#L12-L13

질문은 다음과 같습니다.
Q1. 일반적인 i16, i32, f32.. 등과 같은 primitive type에 대해서 Generic을 사용할 때 위와 같은 접근을 하는 것이 괜찮은 방식인가요? 

Q2. 해당 이슈와 비슷한 형태의 특징을 가진 코드를 작성할 때 참고할만한 Best practice가 있을까요?

감사합니다.

참고:
https://github.com/WICWIU/WICWIU/blob/dcd0dcc326a628a3f5ea1a6158998cf8ca36d4c4/WICWIU_src/Tensor.hpp#L23-L24

**Comment by jeehoonkang** [comment]
아직 const generics가 rust에서 지원되지 않습니다: https://github.com/rust-lang/rust/issues/44580

**Comment by cmpark0126** [comment]
확인했습니다! 감사합니다!
