### ISSUE TITLE
Ownership 관리하는 방법

### ISSUE THREAD

**Issue by cmpark0126** [cmpark0126/wicwiu-rust#2]
안녕하세요 강지훈 교수님. 

현재 wicwiu를 rust로 구현하는 과정에서, ownership을 관리하는 방식에 궁금증이 생겨서 이슈를 남깁니다. 

c++을 이용해서 parameters(weight, bias 등)를 업데이트 하는 Optimizer를 구성할 때는 미리 parameters를 reference할 수 있는 공간을 따로 두었습니다. 그래서 모델 트레이닝 시에 backward 알고리즘이 동작한 이후에 바로 Optimiazer 객체에서 ParameterUpdate를 부르면 reference하고 있는 모든 parameters를 불러서 '구해진' gradient를 사용해서 parameters를 '수정'했습니다.

이 때, '구해진'의 의미는 Optimizer가 아닌 Model에서 parameters가 수정되었다는 의미이고 이 경우는 분명히 mutable한 성질을 가지고 reference 되었다고 생각됩니다. 또한 Optimizer에서 parameters를 '수정'하고자 한다는 것은 그 순간에는 Optimizer 객체 안에서 mutable하게 reference 되어야 한다는 의미를 가진다고 해석됩니다.

질문은 다음과 같습니다.
Q1. 위와 같은 경우 Optimizer나 Model 혹은 제 3의 어떤 다른 공간에서 변수의 ownership을 가지고 있으면 다른 객체에서 해당 변수를 mutable reference하기 위해서는 그 때 마다 ownership을 가진 공간에 요청해서 가져오는 방법을 사용하는 것 밖에는 다른 방도가 없는 것인지 알고싶습니다.

Q2. 이렇게 여러 객체에서 해당 변수를 수정해야 하는 상황이 발생할 경우 보통 어떤 접근을 사용하는지, 이와 관련한 Best Practice가 있는지 알고 싶습니다.

감사합니다.

ps. 현재 이 부분에 대해서 따로 제가 접근한 방식에 대한 코드가 없습니다. 오늘 밤에 제가 나름 생각한 방식으로 접근하여 코드를 작성한 이후 아래에 comment를 남겨두도록 하겠습니다.

**Comment by jeehoonkang** [comment]
`Cell`, `Rc`, `RcCell`, `RefCell`, `UnsafeCell`을 한번 살펴보세요~

**Comment by cmpark0126** [comment]
참고해서 코드를 작성해보겠습니다! 감사합니다!

공부를 조금 더 해야 코드를 작성할 수 있을 것 같습니다.. 우선 최대한 해보겠습니다!
